import {
  TrendingUp,
  ShieldCheck,
  AlertTriangle,
  Rocket,
  Target,
} from "lucide-react";



const analysisCards = [
  {
    title: "Market Opportunity",
    description:
      "AI will analyze your market size, customer demand, and growth potential.",
    icon: TrendingUp,
    color: "text-green-600",
    bg: "bg-green-100",
  },
  {
    title: "Strengths",
    description:
      "Discover the advantages and unique value of your startup idea.",
    icon: ShieldCheck,
    color: "text-blue-600",
    bg: "bg-blue-100",
  },
  {
    title: "Weaknesses",
    description:
      "Identify possible challenges and areas that need improvement.",
    icon: AlertTriangle,
    color: "text-orange-600",
    bg: "bg-orange-100",
  },
  {
    title: "Opportunities",
    description:
      "Find possible growth opportunities and future expansion paths.",
    icon: Rocket,
    color: "text-purple-600",
    bg: "bg-purple-100",
  },
  {
    title: "Threats",
    description:
      "Understand competitors, risks, and possible market problems.",
    icon: Target,
    color: "text-red-600",
    bg: "bg-red-100",
  },
];



function AnalysisGrid() {


  return (

    <section className="mb-10">



      <div className="mb-6">


        <h3
          className="
            text-2xl
            font-bold
            text-[#0F172A]
            dark:text-white
          "
        >
          AI Analysis
        </h3>



        <p
          className="
            text-gray-500
            dark:text-gray-400
            mt-1
          "
        >
          Your startup insights generated by PitchPilot AI.
        </p>



      </div>






      <div
        className="
          grid
          grid-cols-1
          md:grid-cols-2
          lg:grid-cols-3
          gap-6
        "
      >



        {analysisCards.map((card, index) => {


          const Icon = card.icon;



          return (


            <div

              key={index}

              className="
                bg-white
                dark:bg-gray-900
                border
                border-gray-200
                dark:border-gray-700
                rounded-3xl
                p-6
                shadow-sm
                hover:shadow-lg
                transition
                duration-300
              "

            >




              <div
                className={`
                  w-12
                  h-12
                  rounded-2xl
                  ${card.bg}
                  flex
                  items-center
                  justify-center
                  mb-5
                `}
              >

                <Icon
                  size={25}
                  className={card.color}
                />


              </div>







              <h4
                className="
                  text-lg
                  font-bold
                  text-[#0F172A]
                  dark:text-white
                "
              >
                {card.title}
              </h4>







              <p
                className="
                  text-gray-500
                  dark:text-gray-400
                  text-sm
                  leading-relaxed
                  mt-3
                "
              >
                {card.description}
              </p>








              <div
                className="
                  mt-5
                  rounded-xl
                  bg-gray-50
                  dark:bg-gray-800
                  p-4
                  text-sm
                  text-gray-400
                "
              >
                Waiting for AI analysis...
              </div>




            </div>


          );


        })}



      </div>




    </section>

  );


}


export default AnalysisGrid;